### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by a20185** [ConardLi/awesome-cli#4]
`💫  正在执行代码复杂度检测...  ⢿conard cc

选项：
  --help     显示帮助信息                                                 [布尔]
  --version  显示版本号                                                   [布尔]

Error: Failed to load plugin 'html' declared in '.eslintrc': eslint-plugin-html error: It seems that eslint is not loaded. If you think it is a bug, please file a report at https://github.com/BenoitZugmeyer/eslint-plugin-html/issues
    at iterateESLintModules (/Users/souler/Nextcloud/ebproj/eb/node_modules/eslint-plugin-html/src/index.js:65:11)
    at Object.<anonymous> (/Users/souler/Nextcloud/ebproj/eb/node_modules/eslint-plugin-html/src/index.js:36:1)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at ConfigArrayFactory._loadPlugin (/Users/souler/.nvm/versions/node/v14.2.0/lib/node_modules/conard/node_modules/eslint/lib/cli-engine/config-array-factory.js:978:42)
    at /Users/souler/.nvm/versions/node/v14.2.0/lib/node_modules/conard/node_modules/eslint/lib/cli-engine/config-array-factory.js:848:33`

**Comment by yinshipeng** [comment]
同问
